const GET_ALL_FAILED = "GET_ALL_FAILED";
const GET_ALL_REQUEST = "GET_ALL_REQUEST";
const GET_ALL_SUCCESS = "GET_ALL_SUCCESS";
const SEARCH_SHOWS_FAILED = "SEARCH_SHOWS_FAILED";
const SEARCH_SHOWS_REQUEST = "SEARCH_SHOWS_REQUEST";
const SEARCH_SHOWS_SUCCESS = "SEARCH_SHOWS_SUCCESS";
const ADD_TO_FAVORITES = "ADD_TO_FAVORITE";
const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITE";

export {
    GET_ALL_FAILED,
    GET_ALL_REQUEST,
    GET_ALL_SUCCESS,
    SEARCH_SHOWS_FAILED,
    SEARCH_SHOWS_REQUEST,
    SEARCH_SHOWS_SUCCESS,
    ADD_TO_FAVORITES,
    REMOVE_FROM_FAVORITES,
};
