const MARK_COMPLETE = "MARK_COMPLETE";
const MARK_COMPLETE_SUBTODO = "MARK_COMPLETE_SUBTODO";
const ADD_TODO = "ADD_TODO";
const ADD_SUBTODO = "ADD_SUBTODO";
const EDIT_TODO = "EDIT_TODO";
const EDIT_SUBTODO = "EDIT_SUBTODO";
const DELETE_TODO = "DELETE_TODO";
const DELETE_SUBTODO = "DELETE_SUBTODO";
const CREATE_SUBTODO = "CREATE_SUBTODO";

export {
    MARK_COMPLETE,
    MARK_COMPLETE_SUBTODO,
    ADD_TODO,
    ADD_SUBTODO,
    EDIT_TODO,
    EDIT_SUBTODO,
    DELETE_TODO,
    DELETE_SUBTODO,
    CREATE_SUBTODO,
};
